### ISSUE TITLE
0.3 release

### ISSUE THREAD

**Issue by tonyday567** [tonyday567/numhask#94]
0.3 release check-list:

- [x] there are many FIXMEs scattered through the code, many of them easy fixes too.
- [x] there are many TODOs in the last few PRs, and they could be usefully turned into tickets.
- [ ] #106 full haddock coverage
- [x] #107 NumHask.Data.Positive
- [x] #80 & #44 Make a robust tests suite
- [x] #50 (->) instances
- [x] #121 resolution of MonoLocalBinds and Additive usage
- [ ] simple benchmark results

**Comment by LeanderK** [comment]
I will go through the code in the next days and hunt down `TODOs`/`FIXMEs`

**Comment by tonyday567** [comment]
v0.3 launch list below. The ideal would be a release on the arrival of 8.6, and a hot-take blog on deriving-via.

- [ ] #11 deriving-via
- [ ] #106 full haddock coverage
- [ ] #107 NumHask.Data.Positive
- [ ] FIXMEs and TODOs gone
- [ ] #104 hom instances
- [ ] #80 & #44 Make a robust tests suite
- [ ] #50 (->)

Happy to discuss additions and deletions.

**Comment by tonyday567** [comment]
and a new numhask-graph graphic

**Comment by ocramz** [comment]
@tonyday567 @LeanderK switching to `DerivingVia` will force users to GHC > 8.6, which may be a problem. I'm not trying to bikeshed this, but perhaps we can have a dev branch in which we try out the new extension before merging it.

**Comment by tonyday567** [comment]
@ocramz (Welcome Back!) I agree.  I know that DerivingVia should be useful in simplifying usage, but I don't know exactly how yet.  Have updated the todo list to reflect what I see as the remaining issues for a solid release.
